### ISSUE TITLE
[BUG] When "RequestAccessEmail" is set to empty string, "Allow Access Requests" is still enabled.

### ISSUE THREAD

**Issue by jenunn** [pnp/pnpframework#118]
When provisioning out a template to SPO with the property "RequestAccessEmail" with a blank value, "Allow Access Requests" should be disabled, which it does if using SharePointPnPPowerShellOnline - Set-PnPRequestAccessEmails -Email "".

I can see in [this](https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs) file that there is no handling of empty values for provisioning "RequestAccessEmail".

I believe there should be code like this, but don't take my word for it.

![image](https://user-images.githubusercontent.com/58807384/105500148-c1d05980-5cc2-11eb-842a-ecbe29174146.png)

**Comment by jenunn** [comment]
@jansenbe, is this something that is possible to achieve?

**Comment by jenunn** [comment]
@whitehotaru i have not checked this in the latest pnp.powershell, have you?

From what i remember this was the functionality of sharepointpnppowershellonline, which is deprecated.

**Comment by whitehotaru** [comment]
For my environment
```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Darwin 21.6.0
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-InstalledModule PnP.Powershell

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.11.0               PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practic…
```
the way you described it is still valid:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/18051300/185925849-86aca34e-b26a-4de8-80b9-7cca38662b00.png">

```
> Set-PnPRequestAccessEmails -Emails ""
```

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/18051300/185926207-7fa670f8-815e-4862-849a-f7ddc51a9156.png">

Setting it back with `> Set-PnPRequestAccessEmails -Disabled:$false` leads to
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/18051300/185927180-d36c4c3b-2173-46f4-9707-4a13df0e7aa2.png">

Trying this with PnP XML code via `> Invoke-PnPSiteTemplate -Path './Disable Shareing-PnP Template.xml'`

```(XML)
<?xml version="1.0"?>
<pnp:ProvisioningTemplate ID="IntraStopShareing" Version="1" xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema">
	<pnp:WebSettings RequestAccessEmail="" MembersCanShare="false" />
</pnp:ProvisioningTemplate>
```
leads to shareing for members is disabled and email is not touched.
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/18051300/185927905-1aeea044-1551-40b5-9892-6ba3abf32dc7.png">

So the bug was taken over to pnp.powershell. I would love to use PnP XML to be able to set this programatically for an intranet for example.

**Comment by jenunn** [comment]
@jansenbe , is it possible to add this functionality for the pnpframework?

**Comment by jagopauwels** [comment]
It's been 2 years since the last post, but the bug still exists.
