### ISSUE TITLE
Read ASPX pages from Sharepoint

### ISSUE THREAD

**Issue by virav** [pnp/pnpframework#151]
Hi 

I have some requirement to create knowledge repository for bot from more than 800 SharePoint pages. With considering QnAMaker tool's requirement and limitations, we need to export aspx content to html and provide that to QnAMaker. 

If you have any suggestion or thoughts for the same. Currently, I am using “SharePointPnPCoreOnline” and it gives content. But, not in the sequence of FAQ as its displayed on the page and I am looking for more reliable way to get those pages in HTML format.

Please let me know where to look for the solution

**Comment by jansenbe** [comment]
Hi @virav ,

In SharePoint there's a number of page types (from old to new):
- Web part pages: fixed content, allows the user to put web parts
- Wiki pages: MSFT preconfigured layouts, allows the user to add content and web parts
- Publishing pages: customer preconfigures layouts, allows the user to add content and/or web parts
- Modern pages: MSFT preconfigured layout options, allows the user to add content and modern web parts

So getting the page content is not straightforward because it's different for each of these 4 page types. If the content in the 800 pages is still relevant, so it seems, and the content is not in modern SharePoint pages I would recommend [using Page Transformation](http://aka.ms/sharepoint/modernization/pages) to convert all the pages to modern SharePoint pages.

Once pages are in a common format you can think about reading it's content. For modern pages we do have a modern page API that can read a page and list you the "text" parts and the "web parts". For text parts you get HTML snippets that you can process, for web parts you get configuration...which results in HTML when the page is rendered, but that HTML is not available for the API.

**Comment by jansenbe** [comment]
Closing this one as it's an MSFT internal ask raised via internal channels as well.
