### ISSUE TITLE
Publishing a Page template

### ISSUE THREAD

**Issue by roberAlb** [pnp/pnpframework#313]
Hi all,

I have an issue trying to publish a page template. I remember that a page template couldn't be published, I think that the option was even not appearing from interface. Furthermore, documentation says "Template pages are not published; only the pages created from the templates can be published."

 I checked that the PnPFramework code has a condition to not publish the page template which makes sense according to the documentation.

// Publish page, page templates cannot be published
  if (clientSidePage.Publish && !clientSidePage.PromoteAsTemplate)
  {
      page.Publish();
  }

The thing is that now it's possible to publish a page template from the interface. Does this mean that the code should be changed? Or is there another reason why page templates are not published?

Thanks,

**Comment by jansenbe** [comment]
@roberAlb : do you mean there's an option in the UI to publish a page template?

In my tenant I do not (yet) see that:
![image](https://user-images.githubusercontent.com/7451219/117533168-a5df9200-afeb-11eb-979e-a573251d7eaa.png)

**Comment by jansenbe** [comment]
Let me check with the feature owners to see if "publishing" page templates is what was intended here. Thanks for bringing this up @roberAlb .

**Comment by GuillermoBas** [comment]
@jansenbe I think being able to publish templates is fixing another issue that was caused by that situation before.
If you configure a Site Pages library with Approval and draft items visibility only to approves and the author, this will prevent any other contributors in the library to be able to create pages from the existing templates as those will be draft and unless you are the template author you won't be able to see that when creating a page.
Are you 100% sure this is not intended update to how SharePoint manages the Templates?
![image](https://user-images.githubusercontent.com/8668582/117779235-c5bac400-b23e-11eb-9035-f0ec252a795e.png)
