### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eemancini** [pnp/pnpframework#57]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/pnp/PnP-Sites-Core

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Join a site to a hub and gain the hub navigation without impacting the associated site's permissions

#### Observed Behavior
A SharePoint group called "Hub Visitors" is added with Read access to the newly associated site. Sync hub permissions is turned off on the hub site.

#### Steps to Reproduce
I am running version 3.28.2012.0. 

It seems Hub Visitors are only being added when the Team Site is not fully done provisioning. If you run the below code before the permission groups are renamed in "Advanced Site Permissions" to match the site title, you will get the Hub Visitors group. For example, I am making Excellent Team Site. The permission groups first just say Site Owners, Site Members, Site Visitors. If I run now, I get a Hub Visitors group. If I wait until those groups appear as Excellent Team Owners, Excellent Team Members, etc then Hub Visitors is not added.

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.19.2003.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-0598A2406709488081DEB6DB15098DC2">
    <pnp:ProvisioningTemplate ID="TEMPLATE-0598A2406709488081DEB6DB15098DC2" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:WebSettings RequestAccessEmail="" WelcomePage="SitePages/Home.aspx" SiteLogo="" HubSiteUrl="https://eemancini.sharepoint.com/sites/testhub" CommentsOnSitePagesDisabled="false" QuickLaunchEnabled="true" MembersCanShare="true" SearchScope="DefaultScope" SearchBoxInNavBar="Inherit" />
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

If I create a new team site and use the out of the box interface to join to a hub (Settings/Site Information) before the team site is done provisioning, I do not get a Hub Visitors group.

**Comment by eemancini** [comment]
Checking in for help :)

**Comment by jansenbe** [comment]
This seems to be a timing issue, when a site is created it has default groups (because internally SharePoint copies the site from a "blueprint")...and these groups are renamed asynchronously as part of the site provisioning. If you create a site and then immediately apply the template you can get issues, so in those cases it's better to wait for the asynchronous part of the site provisioning to complete before applying the template. 

Not sure how you create the site (code , powershell, tenant template), but for code based provisioning we have https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/Sites/SiteCollection.cs#L776, when using PnP PowerShell there's a [-Wait option on the New-PnPSite cmdlet](https://pnp.github.io/powershell/cmdlets/New-PnPSite.html#-wait).

**Comment by jansenbe** [comment]
@eemancini : did above comment help? If so please let us know so the issue can be closed

**Comment by eemancini** [comment]
Sorry for the delay, @jansenbe. We had a wait as the workaround but I was hoping there was a way to escalate it as it seems like a bug. I now understand if it was I'd need to report that through Microsoft support so I will take it over that way. Thank you for the help :)
