### ISSUE TITLE
PnP.Framework.AuthenticationManager is missing the GetWebLoginClientContext method

### ISSUE THREAD

**Issue by kilasuit** [pnp/pnpframework#94]
In a script that I was using with SharePointPnPPowerShellOnline I was making use of this the following code example to connect to a subsite within a SiteCollection `[OfficeDevPnP.Core.AuthenticationManager]::new().GetWebLoginClientContext($subsite.Url)` 

It seems in the move from `OfficeDevPnP.Core` to `PnP.Framework` this method has been dropped along the way

Is this something that will be coming back in a future release at all? Or has this method been renamed in the process?

**Comment by jansenbe** [comment]
@kilasuit : this method is indeed not available in PnP Framework because PnP Framework is compiled as .NET Standard 2.0 library which works cross platform. The WebLogin logic depends on features not available for .NET Standard 2.0 libraries, so we can't add it back in here. What we however did is add this code base into PnP PowerShell, if you're not using PowerShell your best option at this point is to copy the PnP PowerShell implementation and add that to your code base. See https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/BrowserHelper.cs for the PS implementation that you can reuse.

**Comment by jansenbe** [comment]
Closing as the question has been answered.
